# Project Name
TARGET = Looper

# Sources
CPP_SOURCES = main.cpp globals.cpp utils.cpp controls.cpp looper.cpp bpm.cpp metronome.cpp buffer.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
